version: '3'
services:
  agx_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CLICKHOUSE_URL=http://default:Work12345%21@40.160.52.156:8123?default_format=JSON
    ports:
      - '8080:80'
  volumes: {}
